#ifndef ROBO_STATES_H
#define ROBO_STATES_H

typedef enum RoboStates {				//states for state machine
	STATE_INITIAL = -1,
	STATE_BOOTING = 0,
	STATE_READY = 1,
	STATE_CLEANUP = 2,
	STATE_CHOOSEDIFFICULTY = 30,
	STATE_PLAYORDER = 40,
	STATE_HUMAN_MOVE = 50,
	STATE_WAITING_BROKER = 3,
	STATE_WAITING_USER = 4,
	STATE_MOVE_REQUEST = 5,
	STATE_DETECTED_MOVE = 6,
	STATE_ROBO_MOVE = 7,
	STATE_DONE = 8,
	STATE_ENDGAME = 9,
	STATE_STOPGAME = 10,
	STATE_DISP_EMPTY = 11,
	STATE_DISP_FULL = 12,
	STATE_ALIGN_CAMERA = 13,
	STATE_ALIGN_DONE = 14,
	STATE_HUMAN_ROBOT_INTERACTION = 15,
	STATE_FINISHED = 16
};



#endif // ! ROBO_STATES

