#ifndef ROBO_STATES_H
#define ROBO_STATES_H

typedef enum RoboStates {
STATE_BOOTING = 0,
STATE_READY = 1,
STATE_CHOOSEDIFFICULTY = 30,
STATE_PLAYORDER = 40,
STATE_WAITING_BROKER = 3,
STATE_WAITING_USER = 4,
STATE_MOVE = 5,
STATE_DONE = 6,
STATE_ENDGAME = 7,
STATE_STOPGAME = 8,
STATE_CLEANUP = 9,
STATE_DISP_EMPTY = 11
};



#endif // ! ROBO_STATES

